version: "3.7"

services:
  web:
    build: ./app
    command: gunicorn emagazine.wsgi:application --bind 0.0.0.0:8000 --timeout 90
    volumes:
      - static:/static
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=emagazine
      - POSTGRES_PASSWORD=67SGACCIAHJD0867A5AD
      - POSTGRES_DB=emagazine
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres:
  static:
